@startuml Banco de Dados

entity restaurante{
    pk_restaurante INTERGER NOT NULL <<PK>>
    nome_restaurante VARCHAR NOT NULL
    comissao INTERGER
    email_restaurante VARCHAR NOT NULL
    senha_restaurante VARCHAR NOT NULL
}

entity produto{
    pk_produto INTERGER NOT NULL <<PK>>
    nome_produto VARCHAR NOT NULL 
    preco FLOAT NOT NULL
    pk_restaurante INTERGER <<FK>>
}

restaurante ||--|{ produtos

@enduml